### ISSUE TITLE
Bug: When using foldable/collapsable regions, styles aren't applied to the last lines.

### ISSUE THREAD

**Issue by sandbPublic** [shriprem/FWDataViz#25]
Hi, thanks for creating this plugin.

I observed an issue where creating a foldable region and collapsing it, the style will no longer be applied to the last x visible lines, where x is the number of collapsed/hidden lines. You can produce this simply using one of the sample files like ghcnd-stations.txt, changing the language in the notepad++ language menu to something like C, and add {} with some blank lines to create a collapsable region, then collapse it.

![expanded](https://user-images.githubusercontent.com/9561438/130490969-b5dedeb2-dd7c-46f7-b236-3cf67ae6837a.png)

![collapsed](https://user-images.githubusercontent.com/9561438/130490973-feee4835-3141-401b-9c60-bc68faac7abd.png)

**Comment by shriprem** [comment]
@sandbPublic , Thank you for reporting this issue.

[_As a side note, I was also able to replicate this issue just by selecting a block of lines and then using the NPP menu option: **View » Hide Lines**. The lack of visualization on the last few lines persisted even after scrolling down a page or more._]

The issue was happening due to the distinction between a document's actual line count and the line count displayed in the NPP viewport. This latter count can differ from the document line count due to wordwrapping or line folding or line hiding.

So, it turned out, that fixing this issue also fixed FWDataViz's response when a document is in wordwrap mode. In fact, prior to this fix, the plugin used to display a _Turnoff Wordwrap_ button on the panel, whenever wordwrap was on. As a bonus, this fix has also eliminated that wordwrap limitation.

The fix is available with the [Wordwrap, Fold Lines & Hide Lines Release](https://github.com/shriprem/FWDataViz/releases/tag/v2.1.0.0).

### DLL-only manual upgrade of a previously installed version of the plugin
On the [release](https://github.com/shriprem/FWDataViz/releases/tag/v2.1.0.0) page, download the zip file version to match your Notepad++ bitness. Then, either:
1. In Notepad++, navigate to menu: _Settings » Import » Import Plugins..._ and import the dll file extracted from the zip file.
2. OR, Extract the `FWDataviz.dll` file into the `<NPP_Plugins_folder>/FWDataviz` folder to overwrite the existing DLL therein.

**Comment by sandbPublic** [comment]
Working for me now, thank you.
