### ISSUE TITLE
[Feature Request] - change extension of Themes file

### ISSUE THREAD

**Issue by artie-finkelstein** [shriprem/FWDataViz#27]
Please use .ini or another traditional text file extension for the configuration file currently named Themes.dat.  I note that all the other configuration files use the .ini extension and I believe that .dat is very often used for binary files.  Using .ini makes it much easier to directly edit the file as well as preview it in the Explorer preview pane.

Thank you.

**Comment by shriprem** [comment]
@artie-finkelstein,thank you for your feedback.

1. When the file types and themes are configured inside the plugin's purpose-built editors, the plugin saves backups of their previous versions in the `AppData\Roaming\Notepad++\plugins\Config\FWDataViz\Backup` or the `NPP_Portable_path\plugins\Config\FWDataViz\Backup` common folder. To segregate the file type and themes config files in the backup reload File Open dialog, I had initially opted for them to be with different extensions.
2. At my work's Unix servers, we extensively use .dat files to setup custom environment variables, to provide a list of folders/files/filters/templates/user accounts to be processed by various shell scripts/Perl scripts. And, all these .dat files are in plain text. On the Windows side, I have seen a few games using plain-text .dat files.
3. Although the keys in the Themes config file are in plain text, their values are all in hex code. At least for those not fluent with HTML/CSS color values, it can be argued that this is a binary file.
4. For anyone using Windows File Explorer alternatives, like [Xplorer2](https://www.zabkat.com) or [XYPlorer](https://www.xyplorer.com) or [Multi Commander](http://multicommander.com), configuring them to open files with any extension in NPP is fairly straightforward.

With all that being said, I still find your request reasonable and doable. Moreover, w.r.t. my item no. 1 above, I now find the plugin's config dialog screens to be stable enough to not crash if a user chooses the wrong config file during the backup reloads.

I have implemented your feature request in the [2.1.1.0 Release](https://github.com/shriprem/FWDataViz/releases/tag/v2.1.1.0). Please try it out.

* During the very first load, the plugin will automatically rename the themes config file from _Themes.dat_ to _Themes.ini_.
* In the themes backup reload File Open dialog, I have provided separate _*.ini_ and _*.dat_ file filters. The latter is for users who may want to view backup files saved with the _.dat_ extension.

**Comment by artie-finkelstein** [comment]
Thank you.

I know all the config files are text, which is why I asked for an
extension that traditionally indicates a text file.  I realize almost
any application can be configured to load almost any extension.  That
is not the point.  I doubt you would set the Explorer Preview pane to
view all .exe files as text (as it's an all or nothing setup), well, I
think of .dat files in the same way (my age may be showing here).
Another reason for the request is FWDataViz uses a "move original &
replace with new file" (as versus the "copy file & modify original")
update scheme.  Moving the original effectively blocks using hardlinks
to provide an alternate file type extension; when FWDataViz updates a
config file, the hardlinked name now points to the version in the
backup folder, not the current version.

Another way to protect against users selecting the wrong configuration
file is to put an identification block at the head of each file
denoting it's type and possibly format version, date last updated,
...,   I think most users willing to reconfigure applications by
manually editing .ini files are wise enough to not change things
willy-nilly.  And if I'm wrong, they deserve to have the application
crash.

BTW:  It's a pretty impressive application for handling large, column
oriented, text files.  I thought calling the individual Theme entries
BFBI_?? (as in background foreground bold italic) was a wonderful
self-documenting feature.  It made it much easier to create new themes
by directly editing the .dat/.ini file.

**Comment by shriprem** [comment]
@artie-finkelstein, Thank you for closing this issue and taking the time for this conversation.

[_The numbers in my response below refer to the paragraph numbers in your post._]

1a:  I have three different potential ways to quickly view a file. Firstly, I exclusively use Xplorer2 instead of Windows File Explorer. In Xplorer2, I just use the F4 key to open one or more selected files in NPP. (Even in the WinSCP program that I use for SFTPing to Unix servers, the same F4 key opens files -- both local & remote -- in NPP.) Secondly, the double click action still opens the file in whatever is its default handler. Thirdly, I have also configured the _Send to_ menu in my PC by placing links to various common file handlers in the `%APPDATA%\Microsoft\Windows\SendTo` folder. I just right click and use the _Send to_ option to choose a different viewer for a file. An example handler for this 3rd way is Sandboxie for opening unfamiliar but intriguing exe files.

1b: After reading your post, I put out the [2.1.1.1 Release](https://github.com/shriprem/FWDataViz/releases/tag/v2.1.1.1) today. In this latest version, the config files are backed up using the [CopyFile](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfile) Windows API instead of the earlier [MoveFile](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefile) Windows API. This will enable potential use for hardlinks with the config files. Just this single API call on line #309 was changed in this [file](https://github.com/shriprem/FWDataViz/blob/b0491a12bfd029413a6d22f2886175cc9abae364/src/ConfigIO.cpp).

In Unix, when you use `cp` to copy a file, the copied file will have the then current timestamp instead of the source file timestamp; and, `cp -p` option needs to be used for preserving timestamps. Influenced by this, I mistakenly assumed that the Winows `CopyFile` too will alter the file timestamp, and opted to use `MoveFile` instead. It turns out, `CopyFile` does preserve the source file's timestamp. So, replacing `MoveFile` with `CopyFile` has still left in place my intention of preserving the original timestamps on the backed up config files.

2: When you are halfway in building a fairly large application, you tend to be conservative, and will opt for as many safeguards as possible. So, I had opted to use the File Open dialog's file filter option to segregate the config files with different extensions. I am referring to this dropdown control in the File Open dialog:
![image](https://user-images.githubusercontent.com/45252729/131587817-7428e8b0-04f4-430f-9501-7f6e4ceefe95.png)
But now that the plugin is fully built, I am able to successfully test that loading the wrong config file into either of those editors will not crash them. So, segregating the config files by their extensions does not make much sense any more.

By the way, in the 2.1.1.1 Release, I also have a fix for an issue that had been bothering me for the past several weeks. Please see the first item in the [release notes](https://github.com/shriprem/FWDataViz/releases/tag/v2.1.1.1). Definitely, I must not have been the only one to have noticed it. If it had been reported as an issue here, I would have probably fixed it sooner.

**Comment by artie-finkelstein** [comment]
[The numbers in my response below refer to the paragraph numbers in
your response to the earlier post.]

1a- I too use SendTo to select from alternate viewers, usually for
those files I've not declared as PerceivedType=text in the HKLM hive.
FYI:  .bin & .dat are at the head my "NOT to be perceived as text
list", right after exe/com/obj/lib.

1b- The kids in Redmond have always had to do things their way.

2- No worries.  I don't recall ever seeing that dialog.  I almost
always drag & drop to open files for new projects as it lets me have
more global overview.  Once I'm comfortable with the tools involved
I'll switch to clipboard based operations to manipulate file paths and
then I obviously rely on file open dialogs.

re:  2.1.1.1 release)  I'll redo my earlier testing (actually just
futzing around w/ 2.1.1.0).  Your lexing fix may handle a phantom
issue I thought I saw , but I hadn't nailed down the sequence so I
didn't report anything.

Thank you for such a quick response.
