### ISSUE TITLE
[Bug] Erroneous regex causes crash

### ISSUE THREAD

**Issue by trybowski** [shriprem/FWDataViz#38]
I created an entry with erroneous regexp, like this:
![image](https://user-images.githubusercontent.com/5547901/142736054-296a25e5-bf26-4b67-8768-7520cdd6d200.png)
— plus should've been escaped with backslash!

Result: Notepad++ hung and eventually disappeared. Needs to be fixed.

**Comment by shriprem** [comment]
Application features with user definable regular expressions come with caveats. Fully fool-proofing those features may not be possible. There could always remain some unforeseen edge cases. For example, the most NPP release for v8.1.9.2 contained a fix for crashes  that occurred in the Find/Replace dialog with malformed regular expressions that contained non-ASCII characters. In one instance, the malformed expression was: `[a-é`. See NPP issues [10773](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10773) and [10803](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10803).

With that said, I did review your crash issue.
1. I was able to reproduce the issue with just `+0` or `*0` or `?0` for the regex string. The second plus sign in your regex string didn't have any role in the crash.

2. In both the 64-bit and 32-bit versions of NPP on my machine, there was no actual crash. I only got dozens of message boxes like this:
![image](https://user-images.githubusercontent.com/45252729/142790617-d3b3ea07-33a8-4573-b0c6-9de5e33f6bc2.png)

3. Finally, I would like to point out that you could use a more compact version of the regex string instead of the one you are currently using. You could use: `\+0{16}\+0{15}`. Note that in this compact version, even the second plus sign will need to be escaped to avoid malformation due to the closing bracket sign `}` that immediately precedes it.

I have a build which fixes the crash due to malformed regexes. The regexes in the ADFT lines 1-3 and the Record Regex keys are validated. When validating in the File Type Metadata Editor, messages will be displayed indicating the malformation type and the location of the malformed regex. The regexes are also validated in the plugin panel when loading directly from the ini file. Here at the panel, any malformed regexes are silently ignored to avoid dozens of message boxes otherwise.

Please try out either of the pre-release builds below. I will have a proper release after I have implemented your other enhancement request.

### DLL-only manual upgrade of a previously installed version of the plugin
Download the zip file version to match your Notepad++ bitness. Then, either:
1. In Notepad++, navigate to menu: _Settings » Import » Import Plugins..._ and import the dll file extracted from the zip file.
2. OR, Extract the `FWDataviz.dll` file into the `<NPP_Plugins_folder>/FWDataviz` folder to overwrite the existing DLL therein.

64-bit build: 
[FWDataViz_x64.zip](https://github.com/shriprem/FWDataViz/files/7577902/FWDataViz_x64.zip)

32-bit build:
[FWDataViz_x86.zip](https://github.com/shriprem/FWDataViz/files/7577905/FWDataViz_x86.zip)

**Comment by trybowski** [comment]
Hi Shridhar, thanks for this fix, at first sight it seems to be working. Funny thing though, prior to upgrading the plugin I re-checked the error (having upgraded NPP to ver. 8.1.9.2) and I confirm I did not get any popups, but instead my NPP disappeared without a trace, “just like that”. Oh well, whatever, I guess.

**Comment by shriprem** [comment]
@trybowski, I forgot to mention that I also fixed the automatic filling of the _Record Regex Key_ field based on the input into the _Record Starts With_ field. So, if you had used the _Starts With_ field to generate the regex, the meta character `+` will now be escaped with backslashes. Thus:
![image](https://user-images.githubusercontent.com/45252729/142885904-4f551362-32a2-438b-9728-4c3d7425b3ac.png)

FYI, the fix will also escape all regex meta characters irrespective of their actual significance to the regex parser. Thus:
![image](https://user-images.githubusercontent.com/45252729/142886272-0c0935ab-12a7-4efd-b70c-21df3459a3b2.png)

The automatic escapes may not always align with the intended purpose. In such cases, users should edit the _Record Regex Key_ field directly rather than relying on the conversion from the _Record Starts With_ field.

**Comment by trybowski** [comment]
> The automatic escapes may not always align with the intended purpose. In such cases, users should edit the _Record Regex Key_ field directly rather than relying on the conversion from the _Record Starts With_ field.

Yep, that makes sense.

**Comment by trybowski** [comment]
I confirm that it works correctly now. Thanks!
