### ISSUE TITLE
[Bug] Theme applied incompletely during switching when they have different number of colors defined

### ISSUE THREAD

**Issue by trybowski** [shriprem/FWDataViz#39]
If you switch between themes which have different number of colors defined (in my case 12 vs 2), then colors in positions which don't exist in one of them are not reapplied, and resulting screen shows either a mixture of two themes or a subset of target theme. It looks that number of colors to be applied is taken from old theme instead of new. Switching to another app and back to N++ fixes this.

1. Starting with a colorful theme Tango Stripes:
![image](https://user-images.githubusercontent.com/5547901/142930972-1f2fbd98-5e4d-4e32-a1ba-63d1721011d3.png)

2. Going to change theme to Gray:
![image](https://user-images.githubusercontent.com/5547901/142931119-b39cc93b-66b3-4f19-bc35-0044ec3ff48d.png)

3. I expect this:
![image](https://user-images.githubusercontent.com/5547901/142931295-acb90145-60ac-4506-b961-eba57aecfe0f.png)

4. But I get this:
![image](https://user-images.githubusercontent.com/5547901/142931597-be278488-2649-4a04-920a-7e3c0525bcbf.png)

5. Then I fix it (see screen as in point 3), and I switch from Gray back to Tango Stripes, and again an error:
![image](https://user-images.githubusercontent.com/5547901/142931975-df8108d5-d9c2-414b-ad0c-931c5d8eed4e.png)

Adding my Themes.ini for reference.
[Themes.zip](https://github.com/shriprem/FWDataViz/files/7584263/Themes.zip)

**Comment by shriprem** [comment]
@trybowski, this is happening because a page render event is not firing after a theme selection change in the drop down. Just click anywhere inside the document pane. The render event will fire, and then you should only see the selected theme colors as per expectation.

Just an FYI, this quirk has been there all along, and did not come about from any of the changes in the past few days. I can fix this tiny bug by merely firing a render event after theme selection change. But I will wait on providing you a build until I get feedback from you from the field style enhancement build. Thank you.

**Comment by shriprem** [comment]
@trybowski, as mentioned in my latest [posting](https://github.com/shriprem/FWDataViz/issues/37#issuecomment-975970217) for issue #37, the builds provided there include the fix for the theme rendering issue reported here.

Please try those builds, and feel free to close this issue if you can verify that it has been fixed. Thanks!

**Comment by trybowski** [comment]
It works now. Thank you.
