### ISSUE TITLE
Enhancement: Allow certain record types to be "decorated"

### ISSUE THREAD

**Issue by jeff-bowles** [shriprem/FWDataViz#4]
It would be helpful if certain record types (or even fields within records) could have a boolean property that indicates the record (or field) should be emphasized in some way.

For example, a file might have numerous "documents" within it.  If all of these begin with a particular record type, it would help if a brightly colored horizontal line could be drawn above that record type, effectively adding a visual demarcation of each new document within the file.

**Comment by shriprem** [comment]
FWDataViz is a plugin that is constrained by the APIs of [Notepad++](https://npp-user-manual.org/docs/plugin-communication/) and the [Scintilla](https://www.scintilla.org/ScintillaDoc.html#MessageCategories) text control. Scintilla provides [several API functions](https://www.scintilla.org/ScintillaDoc.html#LongLines) to draw multiple vertical lines to indicate line lengths. But none for horizontal lines.

However, I can think of an alternative to achieve some sort of banding effect within the Scintilla API. And more importantly, do this while not adding much more non-intuitive complexity to the FWDataViz metadata editor UI or compromising the runtime performance of the visualizer algorithm.

I think it might be feasible to provide a choice of color themes at the Record Type level. With such a feature, you could choose to have a custom monochrome theme, with shades of grey, for that demarcation record type; and retain the more colorful theme inherited from the File Type level setting for the other record types.

Since I will be busy with my other obligations during the coming weeks, I will not be able to start work on this feature for a short while.

**Comment by shriprem** [comment]
Jeff, I have added the [Record Type Theme](https://github.com/shriprem/FWDataViz/blob/master/docs/record_type_theme.md) feature. That should allow you to specify distinctive themes to certain record types that serve as section headers or demarcators.

To obtain this latest release files, please go to the [1.0.3.0-RC Release](https://github.com/shriprem/FWDataViz/releases/tag/1.0.3.0-RC) page. Download the zip version to match your Notepad++ bitness. Unzip it into the `<NPP_Plugins_folder>/FWDataviz` folder to overwrite the existing files therein.

Please let me know if you see any regression issues with this build. Appreciate your suggestion for this feature. Please share your feedback.

**Comment by jeff-bowles** [comment]
Shridhar,

I've tried this and it works well!

First, I manually edited the theme file and did not define enough color
patterns.  That caused Notepad++ to abort as soon as I opened FWDataViz.

I corrected the theme file and all is well now.

Thank you for your work!

Jeff
