### ISSUE TITLE
Enhancement: Repeatable "segments"

### ISSUE THREAD

**Issue by jeff-bowles** [shriprem/FWDataViz#7]
Some document types (X12 EDI format comes to mind) allow for certain records to have repeatable groups of fields called segments.  The fields within the segments are all fixed-width, but there may be N number of the same segment type within a record.

EDI file viewing may be beyond the simple design philosophy of FWDataVis.  But it would be an awesome feature!

**Comment by shriprem** [comment]
If no other fields follow those variable count of such segments, then FWDataViz can still handle the visualization of such records. Just define for 10 (or whatever is the expected, reasonable limit) such segments inside your record type specification in the metadata editor. If a _data_ record of that type terminates after only 3 such segments, the plugin will still be able to visualize that record before moving on to the next data record in the file.

Otherwise, the suggested feature will be feasible only in a standalone, custom-built application for such files.
