### ISSUE TITLE
No File Type visible in FWDataViz panel initially

### ISSUE THREAD

**Issue by SKlimaszewskiFDX** [shriprem/FWDataViz#81]
After loading a file and opening the panel the is no visible File Type to choose. After going into File Type Metadata Editor and just clicking "Save as Primary Configuration" and "Close", it's there all of the sudden.

![image](https://user-images.githubusercontent.com/116731096/198032000-85e3e642-c911-4aac-89d9-e2d05718cdc1.png)

**Comment by shriprem** [comment]
As chance would have it, I was on a long flight when you reported this bug. Hence the delay in my response here. Since I will be away for the next 3-4 weeks, with a laptop intended only for basic email and web access, I will not be able to resolve this reported issue until thereafter. Appreciate your patience till then.

**Comment by shriprem** [comment]
@SKlimaszewskiFDX: to test this fix, download the DLL file that matches your installation type (32-bit/64-bit/ARM64) from: https://github.com/shriprem/FWDataViz/actions/runs/3501617891. Then copy the DLL to the`<Notepad++_executable_folder>/plugins/FWDataViz/` folder.

Also, see: #73
