### ISSUE TITLE
Trim Fields for Data Extraction

### ISSUE THREAD

**Issue by SKlimaszewskiFDX** [shriprem/FWDataViz#83]
There is "Trim Field Copy" feature, which works great. But there is no similar feature for Data Extraction, which would be great to have.

**Comment by shriprem** [comment]
As chance would have it, I was on a long flight when you reported this bug. Hence the delay in my response here.

My original intent for the **Data Extraction** feature was that it would serve as a quick reporting tool. Without the padded spaces, the fields will lose the alignment in such a quick report.

That being said, I see that your intention could be to use it as _data transforming_ tool. For example, to output select fields as a comma or tab separated data. In such cases, I agree that trimming spaces would be a desirable option.

Since I will be away for the next 3-4 weeks, with a laptop intended only for basic email and web access, I will not be able to implement this feature until thereafter. Appreciate your patience till then.

**Comment by shriprem** [comment]
This feature is ready for testing.

![image](https://user-images.githubusercontent.com/45252729/202859293-ee4334cf-7996-4a1f-9b78-a29f412ec041.png)

This implementation is pretty basic. But it should suffice your briefly-specified requirement.
* The new checkbox applies across the board for all line items. So, you will need to opt to trim both leading and trailing spaces from all field data, or not trim at all. Providing a separate checkbox on each line item will clutter the UI. Instead, I have plans to implement a more versatile and powerful regex-based find/replace text controls for each line item that will serve much broader data transformation requirements.
* This new option will trim only spaces from field data. Whereas with the _Field Copy_ action on the plugin panel, the trimming option operates on single/multiple/multibyte padding characters (for example, left zero-padding of numeric data).
* The state of the checkbox will be saved within a template if you opt to use templates.

See Discussion #73 for information on downloading the plugin DLL from the most recent commit.
