### ISSUE TITLE
Bug in column navigation (arrows) 

### ISSUE THREAD

**Issue by ShawnDigital** [shriprem/FWDataViz#86]
### Description of the Issue
Column navigation (arrows) near the *Jump to Field* is off by 1 space 

### Steps to Reproduce the Issue
1. Load a file with the visualizer showing
2. Set cursor to beginning of first line 
3. Click the right arrow >

### Expected Behavior
The cursor moves to the first letter of the next field

### Actual Behavior
If *n* is the location of first letter of the next field the cursor moves to n-1 

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows Server 2022 Datacenter (64-bit)
OS Version : 21H2
OS Build : 20348.1850
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    FWDataViz (2.6.2)
    HugeFiles (0.4.1)
    IndentByFold (0.7.3)
    JsonTools (4.10)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (2.9)
    NppConverter (4.5)
    nppcrypt (1.0.1.6)
    NppEditorConfig (0.4)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NPPJSONViewer (2.0.4)
    NppSaveAsAdmin (1.0.211)
    SurroundSelection (1.4.1)
    XMLTools (3.1.1.13)

The definition has start position and width, but this behaves as if its using the character position which starts at 1 with a 0 based index. 

Jump to field works as expected and although it can be hard to tell with cursors and screenshots here is on showing how it set the cursor one character to the left of where it should be.

![image](https://github.com/shriprem/FWDataViz/assets/8883525/76366195-8c4f-4c9a-b914-b2b264a90415)

**Comment by shriprem** [comment]
Shawn, the 'Hop' buttons are serving dual purposes, as has been documented here: https://github.com/shriprem/FWDataViz/blob/master/docs/field_navigation.md#hop-field

I have added emphasis to the key phrase in the following extract from that documentation page:
>More frequently, there is a need to hop to **_the other edge of the current field_** or an adjacent field. For example, you may want to quickly toggle between the left and right alignment selections for Field Copy or Field Paste.

However, if the cursor is already at the extreme edge of the current field, it will move to the extreme edge of the next field in the direction of the hop button. Hence, initially, an extra click is needed to hop to the preceding or next field.

**Comment by ShawnDigital** [comment]
An edge is usually a boundary or outside limitation of something so given a field with width 10 and the cursor (^) being at the beginning of a line or position 1, a "_hop to the other edge of the current field or an adjacent field._" seems to describe jumping to the boundary of the field or...

Before
^1 2 3 4 5 5 7 8 9 10

Expected After
1 2 3 4 5 5 7 8 9 10^

Actual after is...
1 2 3 4 5 5 7 8 9 ^10

So if that is the intended after state, then it works as expected. 

If so I'm not sure _edge_ is the best description of that behavior though so maybe using the numerical position of characters to describe it would be less ambiguous. Either way thank you for taking the time to respond and for sharing your work!

**Comment by shriprem** [comment]
If you imagine each character as a cell or a block, and disregard its left and right edges, the hop actions as they were initially implemented will make complete sense. It may also help if you visualize the caret as a block spanning the full character width instead of a thin vertical pipe at the left of the character.

Left hop would take you to the first character of the field, allowing you to paste some content into the field, left-justified with padding characters to the right. And the right hop would take you to the last character of the same field, allowing you to paste some content, right-justified with padding characters to the left.

That being said, the issue you have raised was also put forth by another user last year. See: #82. So, I have implemented a customizable setting for the right hop action.

Here is the Preferences screen, with the customizable option for 'Hop Right':
![image](https://github.com/shriprem/FWDataViz/assets/45252729/e9419ab5-fbec-449d-b4f6-e6786f9a46d8)

1. First, you will need the plugin DLL from the latest commit [CI build](https://github.com/shriprem/FWDataViz/actions/workflows/CI_build.yml). On the CI Builds page, click on the link for the top (recent) workflow run. Here is the current [direct link](https://github.com/shriprem/FWDataViz/actions/runs/5766732801). This page will have zipped DLLs for x64, x86 & ARM64. For more info on installing the DLL, see: [Downloading FWDataViz.dll file from a commit to the Github repo](https://github.com/shriprem/FWDataViz/discussions/73).
2. For the hop behavior that you are looking to have, you will need to check the box for 'Hop Right...' For more details, see: [Hop Right](https://github.com/shriprem/FWDataViz/blob/master/docs/field_navigation.md#hop-field)
